# Generated by Django 4.1.3 on 2022-11-08 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_doctors'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=250)),
                ('p_phone', models.IntegerField(max_length=15)),
                ('p_email', models.EmailField(max_length=254)),
                ('booking_date', models.DateField()),
                ('booked_on', models.DateField(auto_now=True)),
                ('dep_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.department')),
                ('doc_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.doctors')),
            ],
        ),
    ]
